---

port_profiles:
  pp-dot1x-trunkphone:
    mode: < access | trunk | "trunk phone" > # Specify port mode
    spanning_tree_portfast: edge
    spanning_tree_bpduguard: enabled
    dot1x:
      port_control: auto
      reauthentication: true
      pae:
        mode: authenticator
      host_mode:
        mode: multi-host
        multi_host_authenticated: true
      mac_based_authentication:
        enabled: true
      timeout:
        reauth_period: server
        tx_period: 3
      reauthorization_request_limit: 3

# NOTE:  To not enable multi-host auth comment out the host_mode section

network_ports:

# # ---------------- leaf1/2 ----------------

# - switches:
#     - <switches>
#   # Switch_ports is a list of ranges using AVD range_expand syntax (see link below).
#   # Ex Ethernet1-48 or Ethernet2-3/1-48
#   switch_ports:
#     - <switch_ports>
#   # Port-profile name, to inherit configuration.
#   profile: <trunk phone profile name>
#   native_vlan: 10
#   structured_config:
#     phone:
#       trunk: untagged
#       vlan: <vlan id>
#   dot1x:
#     authentication_failure:
#       action: allow
#       allow_vlan: 999

# - switches:
#     - <switches>
#   # Switch_ports is a list of ranges using AVD range_expand syntax (see link below).
#   # Ex Ethernet1-48 or Ethernet2-3/1-48
#   switch_ports:
#     - <switch_ports>
#   # Port-profile name, to inherit configuration.
#   profile: <access profile name>
#   vlans: <vlan id>
#   dot1x:
#     authentication_failure:
#       action: allow
#       allow_vlan: 999

